name: clibu
description: A tiny library to make the writing of command-line apps intuitive.
version: 1.5.0
homepage: https://github.com/iamtheblackunicorn/cli
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  pedantic: ^1.11.0
