name: clibu # package name
description: A tiny library to make the writing of command-line apps intuitive.
version: 1.0.0
homepage: https://github.com/iamtheblackunicorn/cli
environment:
  sdk: '>=2.8.1 <3.0.0'
dependencies:
  pedantic: ^1.9.0
  dartdoc: ^0.39.0
